spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: api-gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8088}"


  springdoc:
    version: '@springdoc.version@'
    swagger-ui:
      use-root-path: true


